### ISSUE TITLE
Mod imcompatibility - Epicurean Gastronomy

### ISSUE THREAD

**Issue by Luxley** [polgaria/consolehud#3]
Theres an incompatibility with Epicurean Gastronomy
https://github.com/CottonMC/EpicureanGastronomy/issues/18

Played on a 1.14 server that i run.

[latest.log](https://github.com/polgaria/consolehud/files/3205819/latest.log)
[crash-2019-05-22_00.53.39-client.txt](https://github.com/polgaria/consolehud/files/3205820/crash-2019-05-22_00.53.39-client.txt)

**Comment by geniiii** [comment]
you're running on an old version, update the mod; i've already fixed that crash (or at least i hope so)

**Comment by Luxley** [comment]
Is it
